"""Render the cross-repo service mesh as a self-contained HTML file (inline SVG).

No CDN, no JavaScript, no server — a single file you can open anywhere or drop into a README.
Services are laid out on a circle; edges are service->service `calls` (solid, colored by
confidence) and `publishes_to` (dashed purple — async, via a queue/topic).
"""
from __future__ import annotations

import html
import math

from .store.base import KnowledgeStore, RelationshipStore

_EDGE_COLOR = {"high": "#2563eb", "corroborated": "#16a34a", "ambiguous": "#f59e0b",
               "async": "#7c3aed"}
_W, _H = 960, 720


def _positions(n: int) -> list[tuple[float, float]]:
    cx, cy, r = _W / 2, _H / 2, min(_W, _H) * 0.36
    if n == 1:
        return [(cx, cy)]
    return [(cx + r * math.cos(2 * math.pi * i / n - math.pi / 2),
             cy + r * math.sin(2 * math.pi * i / n - math.pi / 2)) for i in range(n)]


def render(knowledge: KnowledgeStore, relationships: RelationshipStore) -> str:
    services = knowledge.list_objects("service")
    ids = [s.id for s in services]
    pos = {sid: p for sid, p in zip(ids, _positions(len(ids)))}

    edges = [e for e in relationships.edges_batch(ids, "calls", "out") if e.to_id in pos]
    edges += [e for e in relationships.edges_batch(ids, "publishes_to", "out") if e.to_id in pos]

    svg = [f'<svg viewBox="0 0 {_W} {_H}" xmlns="http://www.w3.org/2000/svg" '
           f'font-family="system-ui,sans-serif">']
    svg.append('<defs>' + "".join(
        f'<marker id="a-{k}" markerWidth="8" markerHeight="8" refX="7" refY="3" orient="auto">'
        f'<path d="M0,0 L7,3 L0,6 Z" fill="{c}"/></marker>' for k, c in _EDGE_COLOR.items())
        + '</defs>')
    # explicit background: the SVG is also embedded standalone (docs, READMEs), where a
    # transparent canvas would put dark text on a dark theme.
    svg.append(f'<rect width="{_W}" height="{_H}" fill="#ffffff"/>')

    # edges first (under the nodes)
    for e in edges:
        (x1, y1), (x2, y2) = pos[e.from_id], pos[e.to_id]
        conf = "async" if e.relationship == "publishes_to" else e.metadata.get("confidence", "high")
        color = _EDGE_COLOR.get(conf, "#64748b")
        dash = ' stroke-dasharray="5,4"' if conf in ("ambiguous", "async") else ""
        # shorten the line so the arrow lands on the node edge, not its center
        dx, dy = x2 - x1, y2 - y1
        d = math.hypot(dx, dy) or 1
        ex, ey = x2 - dx / d * 12, y2 - dy / d * 12
        svg.append(f'<line x1="{x1:.0f}" y1="{y1:.0f}" x2="{ex:.0f}" y2="{ey:.0f}" '
                   f'stroke="{color}" stroke-width="1.6" opacity="0.75"{dash} '
                   f'marker-end="url(#a-{conf if conf in _EDGE_COLOR else "high"})"/>')

    # nodes
    for s in services:
        x, y = pos[s.id]
        label = html.escape(s.object_id)
        ifc = s.payload.get("interface_count", 0)
        anchor = "start" if x >= _W / 2 else "end"
        lx = x + (12 if anchor == "start" else -12)
        svg.append(f'<circle cx="{x:.0f}" cy="{y:.0f}" r="7" fill="#0ea5e9" stroke="#0369a1"/>')
        svg.append(f'<text x="{lx:.0f}" y="{y + 4:.0f}" text-anchor="{anchor}" '
                   f'font-size="13" fill="#0f172a">{label}'
                   + (f' <tspan fill="#64748b">({ifc})</tspan>' if ifc else "") + '</text>')
    svg.append("</svg>")

    legend = " &nbsp; ".join(f'<span style="color:{c}">&#9632;</span> {k}'
                             for k, c in _EDGE_COLOR.items())
    return f"""<!doctype html><meta charset="utf-8"><title>fleetlens — service mesh</title>
<body style="margin:0;background:#f8fafc;color:#0f172a;font-family:system-ui,sans-serif">
<div style="max-width:1000px;margin:0 auto;padding:24px">
  <h1 style="margin:0 0 4px">Service mesh</h1>
  <p style="margin:0 0 12px;color:#475569">{len(services)} services &middot;
     {len(edges)} dependency edges &middot; node label shows (interface count)</p>
  <div style="font-size:13px;margin-bottom:8px">edge confidence: {legend}</div>
  <div style="background:#fff;border:1px solid #e2e8f0;border-radius:8px">{''.join(svg)}</div>
  <p style="color:#94a3b8;font-size:12px">Generated by fleetlens — deterministic, from source.</p>
</div></body>"""
